env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 
    - error
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
